Rocosa/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;

namespace Rocosa.Models
{
    public class Categoria
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Nombre de categiria es obligatorio")]
        public string NombreCategoria { get; set; }
        [Range(1,int.MaxValue, ErrorMessage ="El orden debe ser mayor a cero")]
        [Required(ErrorMessage = "Orden es obligatorio")]
        public int MostrarOrden { get; set; }
    }
}

Rocosa/Models/ErrorViewModel.cs
namespace Rocosa.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rocosa/Models/TipoAplicacion.cs
using System.ComponentModel.DataAnnotations;

namespace Rocosa.Models
{
    public class TipoAplicacion
    {
        [Key]
        public int Id { get; set; }

        public string Nombre { get; set; }

    }
}

Rocosa/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using Rocosa.Datos;
using Rocosa.Models;
using System.Collections.Generic;

namespace Rocosa.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoriaController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Categoria> Lista = _db.Categoria;
            return View(Lista);
        }
        //Get
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Crear(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _db.Categoria.Add(categoria);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }
        public IActionResult Editar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Categoria.Find(Id);
            if (obj == null)
            {
                return NotFound();

            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Editar(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _db.Categoria.Update(categoria);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        public IActionResult Eliminar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Categoria.Find(Id);
            if (obj == null)
            {
                return NotFound();

            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Eliminar(Categoria categoria)
        {
            if (categoria == null)
            {
                return NotFound();
            }
            _db.Categoria.Remove(categoria);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Rocosa/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Rocosa.Models;
using System.Diagnostics;

namespace Rocosa.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rocosa/Controllers/TipoAplicacionController.cs
using Microsoft.AspNetCore.Mvc;
using Rocosa.Datos;
using Rocosa.Models;
using System.Collections.Generic;

namespace Rocosa.Controllers
{
    public class TipoAplicacionController : Controller
    {
        private readonly ApplicationDbContext _db;

        public TipoAplicacionController(ApplicationDbContext db)
        {
            _db = db;
        }
    
        public IActionResult Index()
        {
            IEnumerable<TipoAplicacion> Lista = _db.TipoAplicacion;
            return View(Lista);
        }
        //Get
        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Crear(TipoAplicacion tipoAplicacion)
        {
            _db.TipoAplicacion.Add(tipoAplicacion);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

Rocosa/Views/Categoria/Crear.cshtml
@model Rocosa.Models.Categoria
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear</h1>

<form method="post" asp-action="Crear">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Nueva categoria</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreCategoria" class="form-label">Nombre categoria</label>
                    <input asp-for="NombreCategoria" class="form-control">
                    <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="MostrarOrden" class="form-label">Mostrar Orden</label>
                    <input asp-for="MostrarOrden" class="form-control">
                    <span asp-validation-for="MostrarOrden" class="text-danger"></span>
                </div>
            </div>
            </br>
            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Crear nueva</button>
                <a asp-controller="Categoria" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{<partial name="_ValidationScriptsPartial"/>}
}

Rocosa/Views/Categoria/Editar.cshtml
@model Rocosa.Models.Categoria
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>
<input asp-for="Id" hidden>
<form method="post" asp-action="Editar">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Editar categoria</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreCategoria" class="form-label">Nombre categoria</label>
                    <input asp-for="NombreCategoria" class="form-control">
                    <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="MostrarOrden" class="form-label">Mostrar Orden</label>
                    <input asp-for="MostrarOrden" class="form-control">
                    <span asp-validation-for="MostrarOrden" class="text-danger"></span>
                </div>
            </div>
            </br>
            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Actualizar</button>
                <a asp-controller="Categoria" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Rocosa/Views/Categoria/Eliminar.cshtml
@model Rocosa.Models.Categoria
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>
<input asp-for="Id" hidden>
<form method="post" asp-action="Eliminar">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-danger pl-3">Esta seguro de eliminar esta categoria?</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="NombreCategoria" class="form-label">Nombre categoria</label>
                    <input asp-for="NombreCategoria" disabled class="form-control">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="MostrarOrden" class="form-label">Mostrar Orden</label>
                    <input asp-for="MostrarOrden" disabled class="form-control">
                </div>
            </div>
            </br>
            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a asp-controller="Categoria" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Rocosa/Views/Categoria/Index.cshtml
@model IEnumerable<Rocosa.Models.Categoria>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de categorias</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Categoria" asp-action="Crear" class="btn btn-primary">
                <i class="fa-solid fa-plus"></i>Nueva categoria
            </a>
        </div>
    </div>
    <br />
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Nombre categoria
                    </th>
                    <th>
                        Orden
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th width="50%">@item.NombreCategoria</th>
                        <th width="30%">@item.MostrarOrden</th>
                        <th class="text-center">
                            <div class="w75 btn-group" role="group">
                                <a asp-controller="Categoria" asp-action="Editar" class="btn btn-primary mx-2" asp-route-Id="@item.Id"><i class="fa-solid fa-pen-to-square"></i></a>
                                <a asp-controller="Categoria" asp-action="Eliminar" class="btn btn-danger mx-2" asp-route-Id="@item.Id"><i class="fa-sharp fa-solid fa-trash"></i></a>
                            </div>
                        </th>
                    </tr>

                }
            </tbody>
        </table>
    }
    else
    {
        <p>No hay registro de categoria</p>
    }
</div>

Rocosa/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Rocosa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rocosa</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Rocosa.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rocosa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoAplicacion" asp-action="Index">Tipo aplicación</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Rocosa - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Rocosa/Views/TipoAplicacion/Crear.cshtml
@model Rocosa.Models.TipoAplicacion
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear</h1>

<form method="post" asp-action="Crear">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Nuevo Tipo Aplicación</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Nombre" class="form-label">Nombre Tipo Aplicación</label>
                    <input asp-for="Nombre" class="form-control">
                </div>
            </div>
            </br>
            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Crear nuevo</button>
                <a asp-controller="TipoAplicacion" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>
        </div>
    </div>
</form>

Rocosa/Views/TipoAplicacion/Index.cshtml
@model IEnumerable<Rocosa.Models.TipoAplicacion>

@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de Tipo Aplicacion</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="TipoAplicacion" asp-action="Crear" class="btn btn-primary">Nuevo Tipo Aplicación</a>
        </div>
    </div>
    <br />
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Tipo Aplicación
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th width="50%">@item.Nombre</th>
                    </tr>

                }
            </tbody>
        </table>
    }
    else
    {
        <p>No hay registro de Tipo aplicación</p>
    }
</div>